CREATE DATABASE DB_TAREFA7;
USE DB_TAREFA7;

CREATE TABLE DISCIPLINA(
IDDISCIPLINA INT PRIMARY KEY AUTO_INCREMENT,
NOMEDISCIPLINA VARCHAR(150) NOT NULL UNIQUE 
);

CREATE TABLE PROFESSOR (
IDPROFESSOR INT PRIMARY KEY AUTO_INCREMENT, 
NOMEPROFESSOR VARCHAR(120) NOT NULL,
EMAILPROFESSOR VARCHAR(150) NOT NULL UNIQUE 
);


CREATE TABLE MINISTRADA (
IDPROFESSOR INT NULL,
IDDISCIPLINA INT NOT NULL,
PRIMARY KEY (IDPROFESSOR,IDDISCIPLINA ),

CONSTRAINT FK_PROF
	FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR),
    
CONSTRAINT FK_DISC
	FOREIGN KEY (IDDISCIPLINA ) REFERENCES DISCIPLINA(IDDISCIPLINA)
       
);


INSERT INTO DISCIPLINA (NOMEDISCIPLINA) VALUE
('Banco de dados I '),
('estrutura de dados'),
('programação orinetada ao objeto'),
('Algoritmo e logica');

INSERT INTO PROFESSOR (NOMEPROFESSOR,EMAILPROFESSOR) VALUE 
('Alice martins ', 'alice.martins@faculdade.edu'),
('Bruno azevedo','bruno.azevedo@faculdade.edu'),
('Carla Nogueira', 'carla.nogueira@faculdade.edu');

INSERT INTO MINISTRADA (IDPROFESSOR,IDDISCIPLINA) VALUE 
(1,1),
(1,2),
(2,1),
(2,3),
(3,4);

SELECT * FROM DISCIPLINA;
SELECT * FROM PROFESSOR;
SELECT * FROM MINISTRADA;

INSERT INTO MINISTRADA (IDPROFESSOR, IDDISCIPLINA) VALUE(1,1);
INSERT INTO MINISTRADA (IDPROFESSOR, IDDISCIPLINA) VALUE(999,1);
INSERT INTO MINISTRADA (IDPROFESSOR, IDDISCIPLINA) VALUE(1,999);

INSERT INTO PROFESSOR (NOMEPROFESSOR,EMAILPROFESSOR)
VALUES ('OUTRO NOME','ALICE.MARTINS@FACULDADE.EDU');



