SELECT VERSION();
SHOW DATABASES;
CREATE DATABASE DBPROJ;
SHOW DATABASES;

USE DBPROJ;

SHOW TABLES;

CREATE TABLE TABPROJ (
idProj INT AUTO_INCREMENT PRIMARY KEY,
NomeProj VARCHAR(100) NOT NULL,
DataInicio DATE,
DataFim DATE
);

SHOW TABLES;

DESCRIBE TABPROJ;

INSERT INTO TABPROJ (NomeProj, DataInicio, DataFim) VALUES
('Sistema Web', '2023-01-15', '2023-06-30'),
('Aplicativo Mobile', '2023-03-01', '2023-09-15'),
('API Backend', '2023-05-10', '2023-12-20'),
('Banco de Dados', '2023-07-01', NULL),
('Infraestrutura Cloud', '2023-08-05', '2024-01-10');

SELECT * FROM TABPROJ;

SELECT * FROM TABPROJ WHERE DataInicio > '2023-05-01';

SELECT
NomeProj AS "PROJETO",
DataInicio AS "DATA_INICIO"
FROM TABPROJ;

SELECT * FROM TABPROJ ORDER BY NomeProj;

SELECT * FROM TABPROJ ORDER BY DataInicio DESC;

SELECT YEAR(DataInicio) AS Ano, COUNT(*) AS QtdeProjetos
FROM TABPROJ
GROUP BY YEAR(DataInicio);















